#!/bin/bash

# Bash script to run the ubertooth-btle command periodically, rotating file names each time

DIR="~/btle/scans_pcap"
TIMER=60

while [ TRUE ]; do
    DATE=`date +"%Y-%m-%d_%T"`
    timeout $TIMER ubertooth-btle -f -q ""$DIR"/bt_$DATE.pcap"
    # sleep 1
done
